<div class="web-zer-wrapper">
    <div class="webinare-content">
        <div class="block-title">Gekaufte Webinare</div>
        <div class="box-content">Schüler mit Lese-Rechtschreibschwäche (LRS) zielgerichtet fördern</div>
        <div class="box-content">Mit digitalen Medien Lernprozesse im Unterricht unterstützen</div>
    </div>
    <div class="zertifikate-content">
        <div class="block-title">Zertifikate</div>
        <div class="box-content">Schüler mit Lese-Rechtschreibschwäche (LRS) zielgerichtet fördern</div>
        <div class="box-content">Gelungene Integration von Kindern mit Migrationshintergrund oder Fluchterfahrungen als Bereicherung für den Schulalltag</div>
    </div>
    <div class="zertifikate-content">
        <div class="block-title"> Seminarunterlagen</div>
        <div class="box-content">Schüler mit Lese-Rechtschreibschwäche (LRS) zielgerichtet fördern</div>
        <div class="box-content">Gelungene Integration von Kindern mit Migrationshintergrund oder Fluchterfahrungen als Bereicherung für den Schulalltag</div>
    </div>
</div>