<?php
/**
 * @var $block Magento\Catalog\Block\Product\View
 * @var $product \Magento\Catalog\Model\Product
 */
$product = $this->getSimpleProduct();
?>
<div class="training_text">
  <div class="training-title">
    <?= __('Mit dem Abschluss der Fortbildung erhalten Sie') ?>
  </div>
  <ul class="inline_list training_points">
    <li><?= __('Lösungen aus der <strong>direkten Schulpraxis</strong>') ?></li>
    <li><?= __('Know-how, dass Sie <strong>sofort in der Praxis</strong> umsetzen können') ?></li>
    <li><?= __('Ihr Teilnehmerzertifikat') ?></li>
  </ul>
</div>
