<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('header-links')
    ->toHtml(); ?>

<nav class="navigation" data-action="navigation">
    <?= /* @escapeNotVerified */ $_menu ?>
    <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
</nav>